#!/bin/sh

#dpkg -L

#kchangelog()

#Escape special chars that the Bourne shell interprets inside double-quotes.
esc()                                                                       
{                                                                           
 echo "$@" | sed 's/\\/\\\\/g;s/\$/\\\$/g;s/`/\\`/g;s/"/\\"/g'
}


#$(uniqueName )
#mkdir

if (echo "$1" | grep -o "[^a-z0-9+.-]")
then
 echo "^ Sorry, that character is illegal in a deb package name."
 exit 1
fi

#Make new /tmp folder. If exists, append "_#"; # increments until it's unique.
base="/tmp/fkdep_$1"
workDir="$base"
i=0;
while [ -e "$name" ]
do
 workDir="$base"_$i
 i=`expr $i + 1`
done
